
version: "3"

services:
  postgres:
    build:
      context: ./psql
      # dockerfile: Dockerfile
    container_name: postgres-test

    ports: 
      - 5432:5432

  nodeapp:
    build:
      context: ./
      # dockerfile: Dockerfile
    container_name: nodeapp

    # ホスト→コンテナへのポートフォワーディング設定：localhost:49161でアクセスすると、コンテナのポート3000に転送される
    ports: 
      - 49161:3000