
version: "3"

services:
  postgres:
    build:
      context: ./psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres-test
    ports: 
      - 5432:5432

  nodeapp:
    build:
      context: ./    
    ports: 
      - 49161:3000
    links:
      - postgresql
    container_name: nodeapp